---
# tasks file for sexy_bash_prompt
# Install sexy-bash-prompt
- name: Install sexy bash prompt
  ansible.builtin.git:
    accept_hostkey: yes
    repo: 'git@github.com:twolfson/sexy-bash-prompt.git'
    dest: /tmp/sexy-bash-prompt

- name: Make sexy bash prompt
  community.general.make:
    chdir: /tmp/sexy-bash-prompt
    target: install

- name: Patch bash_prompt file
  ansible.posix.patch:
    dest: /home/{{ansible_env.USER}}/.bash_prompt
    src: bash_prompt.patch
