---
- name: Local Provisioning
  hosts: localhost
  roles:
  - common_install
  tasks:
  - name: Check if bash prompt is set
    ansible.builtin.stat:
      path: /home/{{ansible_env.USER}}/.bash_prompt
    register: prompt_check
  - name: Install and configure Sexy Bash Prompt
    include_role:
      name: sexy_bash_prompt
    when: not prompt_check.stat.exists
  - name: Check if NeoVim is available
    shell: command -v nvim > /dev/null 2>&1
    register: nvim_check
    ignore_errors: yes
  - name: Install and configure NeoVim
    include_role:
      name: nvim_setup
    when: nvim_check
