---
- name: Local Provisioning
  hosts: localhost
  roles:
  - common_install
  tasks:
  - name: Check if bash prompt is set
    ansible.builtin.stat:
      path: /home/{{ansible_env.USER}}/.bash_prompt
    register: prompt_check
  - name: Install and configure Sexy Bash Prompt
    include_role:
      name: sexy_bash_prompt
    when: not prompt_check.stat.exists
  - name: Check if NodeJS tools are available
    shell: command -v npm > /dev/null 2>&1
    register: nodejs_check
    ignore_errors: yes
  - name: Install NodeJS
    include_role:
      name: nodejs
      apply:
        become: true
    when: nodejs_check.failed == true
  - name: Install and configure NeoVim
    include_role:
      name: nvim_setup
  - name: Install and configure Python and virtualenvs
    include_role:
      name: python
