---
# tasks file for common_install
- name: Check if SSH key exists
  ansible.builtin.stat:
    path: /home/{{ansible_env.USER}}/.ssh/id_rsa
  register: keygen_check

- name: Generate SSH key
  when: keygen_check.stat.exists == False
  community.crypto.openssh_keypair:
    path: /home/{{ansible_env.USER}}/.ssh/id_rsa

- name: Install nvim
  ansible.builtin.package:
    name: nvim
    state: present
