---
# tasks file for common_install
# Create SSH keygen
- name: Check if SSH key exists
  ansible.builtin.stat:
    path: /home/{{ansible_env.USER}}/.ssh/id_rsa
  register: keygen_check

- name: Creates user's SSH directory
  file:
    path: /home/{{ansible_env.USER}}/.ssh
    state: directory

- name: Generate SSH key
  when: keygen_check.stat.exists == False
  community.crypto.openssh_keypair:
    path: /home/{{ansible_env.USER}}/.ssh/id_rsa

# Install tmux
- name: Install tmux
  ansible.builtin.package:
    name: tmux
    state: present
  become: true

# TODO: Create tmux layouts and config

- name: Creates bashrc load directory
  when: install_dropin
  file:
    path: "{{ansible_env.HOME}}/.bashrc.d"
    state: directory

- name: Update bashrc file to load from .bashrc.d folder
  when: install_dropin
  blockinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    block: |
      while read filename
      do
        source "$filename"
      done < <(find -L ~/.bashrc.d -type f)
    marker: '# {mark} ANSIBLE MANAGED BLOCK - bashrc'
    create: yes

