---
# tasks file for python

- name: Install Python
  ansible.builtin.package:
    name: python
    state: present

- name: Install Python-pip
  ansible.builtin.package:
    name: python-pip
    state: present
  become: yes

- name: Install pipenv
  ansible.builtin.package:
    name: python-pipenv
  become: yes

- name: Install pyenv
  ansible.builtin.package:
    name: pyenv
  become: yes

- name: Check if dropin folder exists
  ansible.builtin.stat:
    path: "{{ansible_env.HOME}}/.bashrc.d"
  register: dropin_check

- name: Add alias via dropin
  when: set_alias and dropin_check.stat.exists == True
  ansible.builtin.copy:
    src: python.bashrc
    dest: "{{ansible_env.HOME}}/.bashrc.d/nvim.bashrc"

- name: Add alias via .bashrc
  when: set_alias and dropin_check.stat.exists == False
  blockinfile:
    path: "{{ansible_env.HOME}}/.bashrc"
    create: yes
    marker: "# {mark} ANSIBLE MANAGED BLOCK - Python"
    block: "{{lookup('file', 'python.bashrc')}}"


